### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by codeacula** [codeacula/codeaculas-streamer-tools-api#3]
```
name: "🐛 Bug Report"
description: Report an issue with the project
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report\nThanks for taking the time to report a bug!\n\n🚨 **Before you submit:**\nPlease check [GitHub Discussions](../../discussions) to see if this issue has already been reported."
  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Ex: Twitch chat commands are not responding."
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Describe how to reproduce the issue."
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs"
      render: shell
  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      options:
        - Local Development
        - Self-Hosted
        - Production
  - type: textarea
    id: extra
    attributes:
      label: "Additional Context"
```

```
name: "✨ Feature Request"
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request\nHave an idea for a new feature? Let us know!\n\n💡 **Before you submit:**\nCheck [GitHub Discussions](../../discussions) to see if this idea has been discussed before."
  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Ex: Add a Twitch chat auto-moderation system."
  - type: textarea
    id: problem
    attributes:
      label: "What problem does this solve?"
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
  - type: textarea
    id: extra
    attributes:
      label: "Additional Context"
```

```
name: "🛠 Refactoring / Tech Debt"
description: Propose a code improvement or cleanup
labels: [refactor]
body:
  - type: markdown
    attributes:
      value: "## 🛠 Refactoring / Tech Debt\nSuggest improvements for better code quality.\n\n📝 **Note:** If this is about a new feature, please submit a [Feature Request](../../issues/new?template=feature_request.yml) instead."
  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Ex: Split large Twitch event handler into smaller functions."
  - type: textarea
    id: problem
    attributes:
      label: "What’s the issue?"
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Refactor"
  - type: textarea
    id: extra
    attributes:
      label: "Additional Context"
```
